catalog_name: heiaepgah71pwedmld01001
schema_name: power_consumption

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - Temperature
  - Humidity
  - Wind Speed
  - Hour
  - Day
  - Month
  - general diffuse flows
  - diffuse flows

cat_features:
  - DayOfWeek
  - IsWeekend

target:
  - Zone 1 Power Consumption
  - Zone 2 Power Consumption
  - Zone 3 Power Consumption
