catalog_name: heiaepgah71pwedmld01001
schema_name: power_consumption
pipeline_id: 189007e0-260b-4af1-b220-3ce7f84d9e25

hyperparameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test_hyperparameters:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

processed_features:
  num_features:
    - Temperature
    - Humidity
    - Wind_Speed
    - Hour
    - Day
    - Month
    - general_diffuse_flows
    - diffuse_flows

  cat_features:
    - DayOfWeek_1
    - DayOfWeek_2
    - DayOfWeek_3
    - DayOfWeek_4
    - DayOfWeek_5
    - DayOfWeek_6
    - IsWeekend_1

target:
  target:
    - Zone_1_Power_Consumption
    - Zone_2_Power_Consumption
    - Zone_3_Power_Consumption

dataset:
  raw_data_table: tetuan_city_power_consumption
  num_features:
    - Temperature
    - Humidity
    - Wind_Speed
    - Hour
    - Day
    - Month
    - general_diffuse_flows
    - diffuse_flows

  cat_features:
    - DayOfWeek
    - IsWeekend
