catalog_name: heiaepgah71pwedmld01001
schema_name: power_consumption

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - Temperature
  - Humidity
  - Wind_Speed
  - Hour
  - Day
  - Month
  - general_diffuse_flows
  - diffuse_flows

cat_features:
  - DayOfWeek
  - IsWeekend

target:
  - Zone_1_Power_Consumption
  - Zone_2_Power_Consumption
  - Zone_3_Power_Consumption
